[build]
  command = "npm run build"
  publish = "."

[[redirects]]
  from = "/"
  to = "/templates/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/templates/dashboard.html"
  status = 200

[[redirects]]
  from = "/ppt"
  to = "/templates/ppt.html"
  status = 200